name: My Workflow
on: workflow_dispatch
jobs: 
  first-job:
    run-on: ubuntu latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      _name: Print goodbye
        run: echo "Done - goodbye!"
